### ISSUE TITLE
Help!

### ISSUE THREAD

**Issue by marley03** [GrimKriegor/assistant#3]
On this part:
elseif (LastSaid1=="/sd!") {
        hideChat(1)
        hint("Self Destructed!!!",5)
        selfDestructAll()
    }  
It says:
Else-if keyword (elseif) must be part of an if-statement at line 493, char 9
Help!

**Comment by GrimKriegor** [comment]
@marley03 hello there, and thank you for your interest in the Assistant.

Can you confirm you are running the latest revision of the code, the one provided in this git repository?

I just went in-game and that code revision validated just fine.

_EDIT:_

Anyway a quick and dirty fix could be replacing
`elseif (LastSaid1=="/sd!") {`
with
`if (LastSaid1=="/sd!") {`
