### ISSUE TITLE
Left curly bracket ({) expected after elseif condition at line 1634, char 18

### ISSUE THREAD

**Issue by kaneiskewl** [GrimKriegor/assistant#5]
for some reason the new script you made has a issue. also when I put the curly bracket it then says this Left parenthesis (() expected before condition at line 1634, char 1 then when I put that it says this  Else-if keyword (elseif) must be part of an if-statement at line 1634, char 2 if you could get back to me asap that would be great thank you . :0

**Comment by GrimKriegor** [comment]
That is incredibly strange. 

![2016-07-28-02 42 11-screenshot](https://cloud.githubusercontent.com/assets/1028205/17198478/6ac65f52-546d-11e6-9c7b-079c64a78e3d.jpg)

It validates well for me, could you try this instead?

[grims_assistant_v15-803_nohttp2.txt](https://github.com/GrimKriegor/assistant/files/387533/grims_assistant_v15-803_nohttp2.txt)

**Comment by GrimKriegor** [comment]
Wait, are you copy pasting it from the desktop into the editor, or are you placing the file at "Steam/steamapps/common/GarrysMod/garrysmod/data/expression2/" ?

**Comment by kaneiskewl** [comment]
I placed it into the expression 2 folder and I fixed it it was just some code that wasn't meant to be there but now wen I try to use blinder snake or anything like that I wont work only things like earrape and hide work on this script

**Comment by GrimKriegor** [comment]
I'm not sure I follow, you placed it in the data folder and that fixed it, right?
But now when you try to use any of the major skills like snake or telekinesis, it doesn't work?

**Comment by kaneiskewl** [comment]
um no I deleted the code that said it validated but none of the major skills work
when I turn them on it says they are on they just do not work

**Comment by GrimKriegor** [comment]
That is super strange, I have just tested that file and everything seems to be working fine. Feel free to add me on Steam, I can try to give you the chip ingame and see if that helps.

**Comment by kaneiskewl** [comment]
whats your steam name

**Comment by GrimKriegor** [comment]
Search for "Grim Kriegor".

**Comment by kaneiskewl** [comment]
ok
im mlg pengu

**Comment by kaneiskewl** [comment]
I sent the request
